apiVersion: v1
kind: Service
metadata:
  name: tinyllama-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: tinyllama
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
